version: '3.8'

services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"