server:
  port: 8080

scheduling:
  cron:
    bookingCanselation:  '0 * * * *  ?'

spring:
  application:
    name: spribe-booking

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3
      schema: public
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:db.changelog/changelog-v1.0.xml
    enabled: true
    default-schema: public

logging:
  level:
    root: info
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace